"""update receipts again

Revision ID: f88dc351efbe
Revises: 83e80065441f
Create Date: 2025-01-17 16:08:57.336619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88dc351efbe'
down_revision = '83e80065441f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=120), nullable=True))
        batch_op.drop_column('purchase_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_date', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('date')

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_column('meal_count')

    # ### end Alembic commands ###
